/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projarq;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Guilherme Gama
 */
public class EditPanel extends javax.swing.JPanel {

    EditC c;
    Info[][] mat;
    int s = 14;
    public int type = 0;

    public EditPanel() {
        mat = new Info[s][s];
        for (int i = 0; i < s; i++) {
            for (int j = 0; j < s; j++) {
                mat[i][j] = new Info(0, 0, 0);
            }
        }
        initComponents();
        addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click(evt);
            }
        });
    }

    public void setEditC(EditC ec) {
        c = ec;
    }

    public void load(Info[][] m) {
        for (int i = 0; i < s && i < m.length; i++) {
            for (int j = 0; j < s && j < m.length; j++) {
                Infop.set(mat[i][j], m[i][j].t, m[i][j].x, m[i][j].y);
            }
        }
        repaint();
    }
    
    boolean empty(){
        return Infop.emptyM(mat, s);
    }
    
    boolean wrong(){
        return Infop.wrongM(mat, s);
    }

    int[] xyInMat(int x, int y) {
        float fy = (s * 30 + 10) / (float) getHeight();
        float fx = (s * 30 + 10) / (float) getWidth();
        x = (int) (x * fx) - 10;
        y = (int) (y * fy) - 10;
        if (x < 0 || y < 0 || x % 30 > 20 || y % 30 > 20) {
            return null;
        }
        return new int[]{x / 30, y / 30};
    }

    private int[] lhxy(int x, int y) {
        int lx = x, hx = x, ly = y, hy = y;
        for (int i = x; i >= 0 && mat[i][y].t == 0; i--) {
            lx = i;
        }
        for (int i = x; i < s && mat[i][y].t == 0; i++) {
            hx = i;
        }
        for (int i = y; i >= 0 && mat[x][i].t == 0; i--) {
            ly = i;
        }
        for (int i = y; i < s && mat[x][i].t == 0; i++) {
            hy = i;
        }
        return new int[]{lx - x, hx - x, ly - y, hy - y};
    }

    private void click(java.awt.event.MouseEvent evt) {
        int[] xy = xyInMat(evt.getX(), evt.getY());
        if (xy == null) {
            return;
        }
        int x = xy[0];
        int y = xy[1];
        Info at = mat[x][y];
        if (at.t == 2 && at.x == 0 && at.y == 0) {
            return;
        }

        boolean change;
        if (type != 2) {
            change = mat[x][y].t != type;
            Infop.setM(mat, x, y, at.x, at.y, 0, 0, 0);
            Infop.set(mat[x][y], type, 0, 0);
        } else {
            int[] v = lhxy(x, y);
            v = c.getVarSize(v);
            if (v[0] == 0 && v[1] == 0) {
                return;
            }
            change = true;
            Infop.setM(mat, x, y, at.x, at.y, 0, 0, 0);
            Infop.setM(mat, x, y, v[0], v[1], 2, 0, 0);
            Infop.set(mat[x][y], 2, v[0], v[1]);
        }
        if (change) {
            repaint();
            c.checkObj();
            c.errUpdate();
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        this.setBackground(new Color(240, 240, 240));
        g.setColor(new Color(240, 240, 240));
        g.fillRect(0, 0, getWidth(), getHeight());
        for (int i = 0; i < s; i++) {
            for (int j = 0; j < s; j++) {
                g.setColor(mat[i][j].t == 0 ? Color.WHITE : mat[i][j].t == 1 ? Color.DARK_GRAY : mat[i][j].t == 2 ? Color.GRAY : Color.BLACK);
                g.fillOval(i * 30 + 10, j * 30 + 10, 20, 20);
                g.setColor(Color.BLACK);
                g.drawOval(i * 30 + 10, j * 30 + 10, 20, 20);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
